<h3>Nama: Zulham Azwar Achmad</h3>
<p>Pembahasan kali ini saya akan menjelaskan bagaimana Metode Decision Tree bekerja. Decision Tree itu seperti flowchart, dan dapat membantumu dalam mengambil keputusan berdasarkan pengalaman sebelumnya.</p>
<p>Contoh kali ini, saya menggunakan kasus bagaimana pengambilan keputusan mau main keluar atau engga berdasarkan parameter-parameter yang diberikan seperti, cuaca, keramaian dll. seperti dibawah </p>

<h5> Impor dulu library yang mau dipake ya gaes</h5>

In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
from IPython.display import Image 
from StringIO import StringIO
import pydotplus
from sklearn import preprocessing
from sklearn import tree
import matplotlib.pyplot as plt
import matplotlib.image as pltimg
%matplotlib inline

<h5>baca dulu data dari file excel nya gaes</h5>

In [2]:
df = pd.read_csv('data.csv')
df

      cuaca temperatur kerumunan  berangin   play
0     cerah      panas     ramai     False  False
1     cerah      panas     ramai      True  False
2   mendung      panas     ramai     False   True
3     hujan      sejuk     ramai     False   True
4     hujan     dingin    normal     False   True
5     hujan     dingin    normal      True  False
6   mendung     dingin    normal      True   True
7     cerah      sejuk     ramai     False  False
8     cerah     dingin    normal     False   True
9     hujan      sejuk    normal     False   True
10    cerah      sejuk    normal      True   True
11  mendung      sejuk     ramai      True   True
12  mendung      panas    normal     False   True
13    hujan      sejuk     ramai      True  False

In [3]:
df.berangin = df.berangin.astype(int)
df.play = df.play.astype(int)
df.cuaca = df.cuaca.map({'cerah':0,'mendung':1,'hujan':2})
df.temperatur = df.temperatur.map({'panas':0,'sejuk':1,'dingin':2})
df.kerumunan = df.kerumunan.map({'ramai':0,'normal':1})
df

    cuaca  temperatur  kerumunan  berangin  play
0       0           0          0         0     0
1       0           0          0         1     0
2       1           0          0         0     1
3       2           1          0         0     1
4       2           2          1         0     1
5       2           2          1         1     0
6       1           2          1         1     1
7       0           1          0         0     0
8       0           2          1         0     1
9       2           1          1         0     1
10      0           1          1         1     1
11      1           1          0         1     1
12      1           0          1         0     1
13      2           1          0         1     0

<h5>Sekarang kita kudu nentuin parameter independent nya si X dan parameter dependent si Y, yang nantinya akan jadi outputnya</h5>

In [4]:
features = ['cuaca','temperatur','kerumunan','berangin']
X = df[features]
y = df['play']

<h5>Buat Decision Tree nya lalu simpan dalam bentuk gambar dan ditampilkan</h5>

In [5]:
dtree = tree.DecisionTreeClassifier()
dtree = dtree.fit(X, y)
data = tree.export_graphviz(dtree, out_file=None, feature_names=features)
graph = pydotplus.graph_from_dot_data(data)
graph.write_png('mydecisiontree.png')

img=pltimg.imread('mydecisiontree.png')
imgplot = plt.imshow(img)
plt.show()

NameError: name 'pltimg' is not defined

<h5>Setelah Decision Treenya sudah jadi kita bisa melakukan prediksi</h5

In [ ]:
print(dtree.predict([[1, 1, 0, 1]]))